name: Run bash.sh

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to benchmark (1.x, 2.x, or split)"
        required: true
        default: "1.x"
        type: choice
        options:
          - 1.x
          - 2.x
          - split

jobs:
  all:
    runs-on: self-hosted
    env:
      SKIP_CLONE: true
    steps:
      - uses: actions/checkout@v6
      - name: Checkout timefold-solver
        uses: actions/checkout@v6
        with:
          repository: Christopher-Chianelli/timefold-solver
          ref: ${{ github.event.inputs.version == 'split' && 'perf/split-random' || (github.event.inputs.version == '2.x' && 'main' || '1.x') }}
          path: timefold-solver
      - name: Checkout timefold-solver-enterprise
        uses: actions/checkout@v6
        with:
          repository: TimefoldAI/timefold-solver-enterprise
          ref: ${{ github.event.inputs.version == 'split' && 'perf/split-random' || (github.event.inputs.version == '2.x' && 'main' || '1.x') }}
          path: timefold-solver-enterprise
      - name: Checkout timefold-quickstarts
        uses: actions/checkout@v6
        with:
          repository: TimefoldAI/timefold-quickstarts
          ref: ${{ github.event.inputs.version == 'split' && 'development' || (github.event.inputs.version == '2.x' && 'development' || 'development-1.x') }}
          path: timefold-quickstarts
      - run: bash ./benchmark.sh ${{ inputs.version }}
